/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.RoleSpa;

/**
 *
 * @author anky
 */
public class RequestSpaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestSpaJPanel
     */
    public RequestSpaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        enterprice = new javax.swing.JLabel();
        valuejLabel = new javax.swing.JLabel();
        messagejLabel = new javax.swing.JLabel();
        messagejTextField = new javax.swing.JTextField();
        RequetsjButton = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setBackground(new java.awt.Color(163, 206, 215));
        backJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backJButton.setText("Back");
        backJButton.setBorder(null);
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        enterprice.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        enterprice.setText("Enterprise: ");
        add(enterprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        valuejLabel.setText("<value>");
        add(valuejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 50, -1));

        messagejLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        messagejLabel.setText("Message");
        add(messagejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));
        add(messagejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 190, -1));

        RequetsjButton.setBackground(new java.awt.Color(163, 206, 215));
        RequetsjButton.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        RequetsjButton.setText("Request Appointment");
        RequetsjButton.setBorder(null);
        add(RequetsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 190, 30));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/spa_img.jpg"))); // NOI18N
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 460));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RequetsjButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterprice;
    private javax.swing.JLabel image;
    private javax.swing.JLabel messagejLabel;
    private javax.swing.JTextField messagejTextField;
    private javax.swing.JLabel valuejLabel;
    // End of variables declaration//GEN-END:variables
}
