/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.RoleDietician;

/**
 *
 * @author anky
 */
public class WorkAreaDieticianJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkAreaDieticianJPanel
     */
    public WorkAreaDieticianJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        organization = new javax.swing.JLabel();
        value = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        declineJButton = new javax.swing.JButton();
        imagelabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organization.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        organization.setText("Organization");
        add(organization, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 30, 100, 40));

        value.setText("<value>");
        add(value, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        workRequestJTable.setBackground(new java.awt.Color(0, 153, 255));
        workRequestJTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 7, true));
        workRequestJTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender", "Reciver", "Status"
            }
        ));
        workRequestJTable.setSelectionBackground(new java.awt.Color(231, 200, 237));
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 610, 140));

        assignJButton.setBackground(new java.awt.Color(231, 200, 237));
        assignJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        assignJButton.setForeground(new java.awt.Color(255, 255, 255));
        assignJButton.setText("Assign Request");
        assignJButton.setBorder(null);
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 120, 30));

        processJButton.setBackground(new java.awt.Color(231, 200, 237));
        processJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        processJButton.setForeground(new java.awt.Color(255, 255, 255));
        processJButton.setText("Process Request");
        processJButton.setBorder(null);
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 130, 30));

        declineJButton.setBackground(new java.awt.Color(231, 200, 237));
        declineJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        declineJButton.setForeground(new java.awt.Color(255, 255, 255));
        declineJButton.setText("Decline Request");
        declineJButton.setBorder(null);
        add(declineJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 130, 30));

        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dietimage.jpg"))); // NOI18N
        add(imagelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processJButtonActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton declineJButton;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel organization;
    private javax.swing.JButton processJButton;
    private javax.swing.JLabel value;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
